swagger: '2.0'
info: {title: WeSmart, description: WeSmart Documentation, version: 2.1.0}
host: api.wesmart.com
schemes: [https]
tags:
- {name: dashboard, description: Action on Project Dashboard}
- {name: lynx, description: Action on Lynx}
- {name: authorization, description: Action on Authorization}
- {name: user, description: Action on User}
- {name: project, description: Action on Project}
- {name: application, description: Action on Project Application}
- {name: collaborator, description: Action on Project Collaborator}
- {name: notification, description: Action on Notifcation and Channel}
- {name: device, description: Action on Project Device}
- {name: stream, description: Action on Device Stream}
- {name: report, description: Action on Project Report}
- {name: weather, description: Action on Weather}
- {name: prediction, description: Action on Prediction}
- {name: alert, description: Action on Project Alert}
securityDefinitions:
  WeSmartAuth:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://api.wesmart.com/oauth/authorize
    tokenUrl: https://api.wesmart.com/oauth/token
    scopes: {project.dashboard.read: Read permission on Project Dashboard, project.dashboard.write: Write
        permission on Project Dashboard, authorization.read: Read permission on Authorization,
      authorization.write: Write permission on Authorization, notification.admin: Admin
        permission on Notification, notification.read: Read permission on Notification,
      notification.write: Write permission on Notification, profile.read: Read permission
        on Profile, profile.write: Write permission on Profile, project.admin: Admin
        permission on Project, project.create: Create permission on Project, project.read: Read
        permission on Project, project.write: Write permission on Project, project.application.read: Read
        permission on Project Application, project.application.write: Write permission
        on Project Application, project.metadata.read: Read permission on metadata,
      project.metadata.write: Write permission on metadata (here bills), project.device.read: Read
        permission on Project Device, project.device.write: Write permission on Project
        Device, project.report.read: Read permission on Project Report, project.report.write: Write
        permission on Project Report, weather.read: Read permission on Weather, project.alert.read: Read
        permission on Project Alert, project.alert.write: Write permission on Project
        Alert}
paths:
  /project/{projectId}/dashboard:
    get:
      tags: [dashboard]
      summary: List Project Dashboard
      description: Get a list of Dashboard of the `Project`.
      operationId: listDashboard
      security:
      - WeSmartAuth: [project.dashboard.read]
    post:
      tags: [dashboard]
      summary: Create Project Dashboard
      description: Create a new Dashboard
      operationId: createDashboard
      security:
      - WeSmartAuth: [project.dashboard.write]
  /project/{projectId}/dashboard/{dashboardId}:
    get:
      tags: [dashboard]
      summary: Get Project Dashboard
      description: Get Project Dashboard information
      operationId: getDashboard
      security:
      - WeSmartAuth: [project.dashboard.read]
    put:
      tags: [dashboard]
      summary: Update Project Dashboard
      description: Update Project Dashboard information
      operationId: updateDashboard
      security:
      - WeSmartAuth: [project.dashboard.write]
    delete:
      tags: [dashboard]
      summary: Delete Project Dashboard
      description: Delete a Project Dashboard.
      operationId: deleteDashboard
      security:
      - WeSmartAuth: [project.dashboard.write]
  /{keyspace}/dump:
    get:
      tags: [lynx]
      summary: Dump data
      description: Dump all data of the keyspace.
      operationId: dumpData
  /{keyspace}/ingest:
    post:
      tags: [lynx]
      summary: Push data
      description: Push new data on the keyspace or overwrite existing values.
      operationId: pushData
  /{keyspace}/query:
    post:
      tags: [lynx]
      summary: Query data
      description: Query data on the keyspace.
      operationId: queryData
    delete:
      tags: [lynx]
      summary: Delete data
      description: Delete data on the keyspace.
      operationId: deleteData
  /authorization:
    get:
      tags: [authorization]
      summary: List Authorizations
      description: List the user Authorizations
      operationId: listAuthorizations
      security:
      - WeSmartAuth: [authorization.read]
  /authorization/{jti}:
    delete:
      tags: [authorization]
      summary: Delete Authorization
      description: Delete an Authorization
      operationId: deleteAuthorization
      security:
      - WeSmartAuth: [authorization.write]
  /project:
    get:
      tags: [project]
      summary: List Project
      description: Get the list of `Project` the user has access to.
      operationId: listProjects
      security:
      - WeSmartAuth: [project.read]
    post:
      tags: [project]
      summary: Create Project
      description: Create a new `Project`
      operationId: createProject
      security:
      - WeSmartAuth: [project.create]
  /project/{projectId}:
    get:
      tags: [project]
      summary: Get Project information
      description: Get a `Project`
      operationId: getProject
      security:
      - WeSmartAuth: [project.read]
    put:
      tags: [project]
      summary: update Project information
      description: Update a `Project`
      operationId: UpdateProject
      security:
      - WeSmartAuth: [project.write]
    delete:
      tags: [project]
      summary: Delete Project
      description: Set a `Project` for deletion
      operationId: deleteProject
      security:
      - WeSmartAuth: [project.write]
  /project/{projectId}/collaborator:
    get:
      tags: [collaborator]
      summary: List Project collaborators
      description: Get a list of collaborator of the `Project`.
      operationId: listProjectCollaborators
      security:
      - WeSmartAuth: [project.read]
  /project/{projectId}/collaborator/{userId}:
    put:
      tags: [collaborator]
      summary: Add Project User
      description: Add a new collaborator to the `Project` or edit the permissions
        of an existing one.
      operationId: addProjectCollaborator
      security:
      - WeSmartAuth: [project.admin]
    delete:
      tags: [collaborator]
      summary: Remove Project User
      description: Remove a collaborator from the `Project`
      operationId: deleteProjectCollaborator
      security:
      - WeSmartAuth: [project.admin]
  /user:
    post:
      tags: [user]
      summary: Invite User
      description: Invite a new `User`
      operationId: inviteUser
  /user/{userId}:
    get:
      tags: [user]
      summary: Get User informations
      description: Get informations of the `User`. You can only get your own information
        (use the `/user/me` endpoint) unless you are an Admin of the application.
      operationId: getUser
      security:
      - WeSmartAuth: [profile.read]
    put:
      tags: [user]
      summary: Update User
      description: Update the `User` information.
      operationId: updateUser
      security:
      - WeSmartAuth: [profile.write]
    delete:
      tags: [user]
      summary: Delete User
      description: Delete a `User`. Only admin can delete execute this call.
      operationId: deleteUser
      security:
      - WeSmartAuth: [profile.write]
  /user/me:
    get:
      tags: [user]
      summary: Get my informations
      description: Get informations of the connected `User`.
      operationId: getMe
      security:
      - WeSmartAuth: [profile.read]
    put:
      tags: [user]
      summary: Update User
      description: Update the connected `User` information.
      operationId: updateMe
      security:
      - WeSmartAuth: [profile.write]
  /user/suggest:
    post:
      tags: [user]
      summary: Suggest User
      description: Make a request to find a `User` based on the query send.
      operationId: suggestUser
  /project/{projectId}/application:
    get:
      tags: [application]
      summary: List Project Application
      description: Get a list of Application of the `Project`.
      operationId: listApplication
      security:
      - WeSmartAuth: [project.application.read]
    post:
      tags: [application]
      summary: Create Project Application
      description: Create a new Application
      operationId: createApplication
      security:
      - WeSmartAuth: [project.application.write]
  /project/{projectId}/application/{applicationId}:
    get:
      tags: [application]
      summary: Get Project Application
      description: Get Project Application information
      operationId: getApplication
      security:
      - WeSmartAuth: [project.application.read]
    put:
      tags: [application]
      summary: Update Project Application
      description: Update Project Application information
      operationId: updateApplication
      security:
      - WeSmartAuth: [project.application.write]
    delete:
      tags: [application]
      summary: Delete Project Application
      description: Delete a Project Application. Can only be used by project admin
      operationId: deleteApplication
      security:
      - WeSmartAuth: [project.admin]
  /notification:
    get:
      tags: [notification]
      summary: List Notification
      description: Get a list of Notification
      operationId: listNotification
      security:
      - WeSmartAuth: [notification.read]
    post:
      tags: [notification]
      summary: Create Notification
      description: Create a new Notification
      operationId: createNotification
      security:
      - WeSmartAuth: [notification.write]
    head:
      tags: [notification]
      summary: List Notification
      description: Get a list of notification
      operationId: patchNotification
      security:
      - WeSmartAuth: [notification.read]
  /notification/{notificationId}:
    get:
      tags: [notification]
      summary: Get Notification
      description: Get information of the Notification
      operationId: getNotification
      security:
      - WeSmartAuth: [notification.read]
    put:
      tags: [notification]
      summary: Update Notification
      description: Update a Notification
      operationId: updateNotification
      security:
      - WeSmartAuth: [notification.read]
  /notification/channel:
    get:
      tags: [notification]
      summary: List Notification Channel
      description: Get a list of Channel
      operationId: listChannel
      security:
      - WeSmartAuth: [notification.admin]
    post:
      tags: [notification]
      summary: Create Channel
      description: Create a new Channel
      operationId: createChannel
      security:
      - WeSmartAuth: [notification.admin]
  /notification/channel/{channelId}:
    get:
      tags: [notification]
      summary: Get Channel information
      description: Get the information of the Channel
      operationId: getChannel
      security:
      - WeSmartAuth: [notification.admin]
    put:
      tags: [notification]
      summary: Update Channel
      description: Update the information of the Channel.
      operationId: updateChannel
      security:
      - WeSmartAuth: [notification.admin]
    delete:
      tags: [application]
      summary: List Project Application
      description: Get a list of Application of the `Project`.
      operationId: deleteChannel
      security:
      - WeSmartAuth: [notification.admin]
  /project/{projectId}/calendar/event/{eventId}:
    get:
      tags: [calendar]
      summary: Get an event
      description: Get an event by its ID
      operationId: getEvent
    delete:
      tags: [calendar]
      summary: Delete an Event
      description: Delete a Event by its ID
      operationId: deleteEvent
  /project/{projectId}/calendar/:
    post:
      tags: [calendar]
      summary: Import Events
      description: Import a file containing a list of events.
      operationId: importFileCalendar
  /project/{projectId}/calendar/event:
    get:
      tags: [calendar]
      summary: Get all the events
      description: Get all the events for the project.
      operationId: getEvents
  /project/{projectId}/calendar/manual:
    post:
      tags: [calendar]
      summary: add events
      description: add a list of events.
      operationId: addEventsManual
      security:
      - WeSmartAuth: [project.metadata.write]
  /project/{projectId}/calendar/query:
    post:
      tags: [calendar]
      summary: query events
      description: get list of events involved in a time interval
      operationId: queryEvents
  /project/{projectId}/device:
    get:
      tags: [device]
      summary: List Project Device
      description: Get a list of Device of the `Project`.
      operationId: listDevice
      security:
      - WeSmartAuth: [project.device.read]
    post:
      tags: [device]
      summary: Create Project Device
      description: Create a new Device
      operationId: createDevice
      security:
      - WeSmartAuth: [project.device.write]
  /project/{projectId}/device/{deviceId}:
    get:
      tags: [device]
      summary: Get Project Device
      description: Get Project Device information
      operationId: getDevice
      security:
      - WeSmartAuth: [project.device.read]
    put:
      tags: [device]
      summary: Update Project Device
      description: Update Project Device information
      operationId: updateDevice
      security:
      - WeSmartAuth: [project.device.write]
    delete:
      tags: [device]
      summary: Delete Project Device
      description: Delete a Project Device
      operationId: deleteDevice
      security:
      - WeSmartAuth: [project.device.write]
  /project/{projectId}/device/{deviceId}/stream:
    get:
      tags: [stream]
      summary: List Project Device Stream
      description: Get a list of Stream of the Device of the `Project`.
      operationId: listStream
      security:
      - WeSmartAuth: [project.device.read]
    post:
      tags: [stream]
      summary: Create Device Stream
      description: Create a new Stream
      operationId: createStream
      security:
      - WeSmartAuth: [project.device.write]
  /project/{projectId}/device/{deviceId}/stream/{streamId}:
    get:
      tags: [stream]
      summary: Get Device Stream
      description: Get Device Stream information
      operationId: getStream
      security:
      - WeSmartAuth: [project.device.read]
    put:
      tags: [stream]
      summary: Update Device Stream
      description: Update Device Stream information
      operationId: updateStream
      security:
      - WeSmartAuth: [project.device.write]
    delete:
      tags: [stream]
      summary: Delete Device Stream
      description: Delete a Device Stream
      operationId: deleteStream
      security:
      - WeSmartAuth: [project.device.write]
  /unit:
    get:
      tags: [device]
      summary: List Unit
      description: List available Units
      operationId: listUnit
  /project/{projectId}/device/dump:
    get:
      tags: [device]
      summary: Dump Device data
      description: Dump all data of all device in the project.
      operationId: dumpDeviceData
      security:
      - WeSmartAuth: [project.device.read]
  /project/{projectId}/device/ingest:
    post:
      tags: [device]
      summary: Push Device data
      description: Push new data on the device or overwrite existing values.
      operationId: pushDeviceData
      security:
      - WeSmartAuth: [project.device.write]
  /project/{projectId}/device/query:
    post:
      tags: [device]
      summary: Query Device data
      description: Query data on the Project Device.
      operationId: queryDeviceData
      security:
      - WeSmartAuth: [project.device.write]
  /project/{projectId}/bill/file/{fileId}:
    get:
      tags: [bill]
      description: get a file with its Id.
      summary: get a file
    delete:
      tags: [bill]
      summary: Delete a file
      description: Delete the file you want by its ID
      operationId: deleteFile
  /project/{projectId}/bill/file:
    post:
      tags: [bill]
      summary: import a bill
      description: import a bill file of energy consumption and get its metadata.
      operationId: postBill
    get:
      tags: [bill]
      summary: Get files
      description: get uploaded files for the project
  /project/{projectId}/bill/{fileId}:
    post:
      tags: [bill]
      summary: Query chosen columns
      description: Send the columns that you want to import and register it.
      operationId: registerBill
      security:
      - WeSmartAuth: [project.metadata.write]
  /data-provider:
    get:
      tags: [bill]
      summary: Get list of providers
      description: Get list of providers that you can handle file upload
      operationId: getProvider
      security:
      - WeSmartAuth: [project.metadata.write]
  /project/{projectId}/report:
    get:
      tags: [report]
      summary: List Project Report
      description: Get a list of Report of the `Project`.
      operationId: listReport
      security:
      - WeSmartAuth: [project.report.read]
    post:
      tags: [report]
      summary: Create Project Report
      description: Create a new Report
      operationId: createReport
      security:
      - WeSmartAuth: [project.report.write]
  /project/{projectId}/report/{reportId}:
    get:
      tags: [report]
      summary: Get Project Report
      description: Get Project Report information
      operationId: getReport
      security:
      - WeSmartAuth: [project.report.read]
    put:
      tags: [report]
      summary: Update Project Report
      description: Update Project Report information
      operationId: updateReport
      security:
      - WeSmartAuth: [project.report.write]
    delete:
      tags: [report]
      summary: Delete Project Report
      description: Delete a Project Report.
      operationId: deleteReport
      security:
      - WeSmartAuth: [project.report.write]
  /weather:
    post:
      tags: [weather]
      summary: Query Weather
      description: Get Weather data for a location during a period
      operationId: queryWeather
      security:
      - WeSmartAuth: [weather.read]
  /weather/icon:
    get:
      tags: [weather]
      summary: List Icon
      description: Get Weather icon mapping
      operationId: listIcon
      security:
      - WeSmartAuth: [weather.read]
  /project/{projectId}/forecast/query:
    post:
      tags: [prediction]
      summary: Make forecast
      description: Make a forecast to predict device data
      operationId: forecast
      security:
      - WeSmartAuth: [project.device.read, weather.read]
  /project/{projectId}/alert:
    get:
      tags: [alert]
      summary: List Project Alert
      description: Get a list of Alert of the `Project`.
      operationId: listAlert
      security:
      - WeSmartAuth: [project.alert.read]
    post:
      tags: [alert]
      summary: Create Project Alert
      description: Create a new Alert
      operationId: createAlert
      security:
      - WeSmartAuth: [project.alert.write]
  /project/{projectId}/alert/{alertId}:
    get:
      tags: [alert]
      summary: Get Project Alert
      description: Get Project Alert information
      operationId: getAlert
      security:
      - WeSmartAuth: [project.alert.read]
    put:
      tags: [alert]
      summary: Update Project Alert
      description: Update Project Alert information
      operationId: updateAlert
      security:
      - WeSmartAuth: [project.alert.write]
    delete:
      tags: [alert]
      summary: Delete Project Alert
      description: Delete a Project Alert
      operationId: deleteAlert
      security:
      - WeSmartAuth: [project.alert.write]
  /project/{projectId}/alert/{alertId}/event:
    get:
      tags: [alert]
      summary: List Project Alert Event
      description: Get a list of Event of the Alert of the `Project`.
      operationId: listEvent
      security:
      - WeSmartAuth: [project.alert.read]
  /project/{projectId}/alert/{alertId}/event/{eventId}:
    put:
      tags: [alert]
      summary: Update Alert Event
      description: Update Alert Event information
      operationId: updateEvent
      security:
      - WeSmartAuth: [project.alert.write]
    delete:
      tags: [alert]
      summary: Delete Alert Event
      description: Delete a Alert Event
      operationId: deleteEvent
      security:
      - WeSmartAuth: [project.alert.write]